<h3>Novo User</h3>

<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'users','action'=>'new')); ?>">Novo</a>
</p>

<br />

<?php

$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin',array('controller'=>'users','action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'))."<br />";
echo $this->form()->closeTag();
?>
